'use client'

import { useState, useRef } from 'react'
import {
  FileText,
  CheckCircle2,
  ShieldAlert,
  HelpCircle,
  Lightbulb,
  CalendarDays,
  ListChecks,
  RotateCcw,
  Download,
  FileDown,
  Copy,
  CheckCheck,
  Share2,
  Users,
} from 'lucide-react'
import { toast } from 'sonner'
import type { ActionPlanResult } from '../data/samples'
import { exportToMarkdown, buildMarkdownString } from '../lib/exportMarkdown'
import { trackNovus } from '../lib/novus'
import ActionTable from './ActionTable'
import Timeline from './Timeline'

interface ResultsSectionProps {
  result: ActionPlanResult
  onReset: () => void
  isSharedView?: boolean
}

// ─── Confidence score calculation ────────────────────────────────────────────

function calculateConfidence(result: ActionPlanResult): number {
  let score = 45
  score += Math.min(result.tasks.length * 2, 12)
  const withOwners = result.tasks.filter(
    (t) => t.owner && !['tbd', '—', '-'].includes(t.owner.toLowerCase()),
  ).length
  score +=
    result.tasks.length > 0
      ? Math.round((withOwners / result.tasks.length) * 15)
      : 0
  const withDeadlines = result.tasks.filter(
    (t) => t.deadline && !['tbd', '—', '-'].includes(t.deadline.toLowerCase()),
  ).length
  score +=
    result.tasks.length > 0
      ? Math.round((withDeadlines / result.tasks.length) * 12)
      : 0
  score += Math.min(result.risks.length * 2, 8)
  score += Math.min(Math.round(result.decisions.length * 1.5), 6)
  score += Math.min(result.timeline.length, 5)
  return Math.min(Math.round(score), 100)
}

// ─── Jira export builder ─────────────────────────────────────────────────────

function buildJiraString(result: ActionPlanResult): string {
  const lines: string[] = []
  lines.push('== ACTIONFLOW AI — JIRA EXPORT ==')
  lines.push(
    `Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
  )
  lines.push('')
  result.tasks.forEach((t) => {
    lines.push('---')
    lines.push(`[${t.id}] ${t.title}`)
    lines.push('')
    lines.push(`Task: ${t.title}`)
    lines.push(`Owner: ${t.owner}`)
    lines.push(`Priority: ${t.priority}`)
    lines.push(`Deadline: ${t.deadline}`)
    lines.push(`Status: ${t.status}`)
    lines.push('Description: [Add context from meeting transcript]')
    lines.push('')
  })
  if (result.risks.length > 0) {
    lines.push('---')
    lines.push('RISKS & BLOCKERS:')
    result.risks.forEach((r) => lines.push(`• ${r}`))
    lines.push('')
  }
  return lines.join('\n')
}

// ─── Notion export builder ───────────────────────────────────────────────────

function buildNotionString(result: ActionPlanResult): string {
  const lines: string[] = []
  lines.push('# ActionFlow Plan')
  lines.push('')
  lines.push(
    `*Generated by ActionFlow AI · ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}*`,
  )
  lines.push('')
  lines.push('---')
  lines.push('')
  lines.push('## Summary')
  lines.push('')
  lines.push(result.summary)
  lines.push('')
  lines.push('---')
  lines.push('')
  if (result.tasks.length > 0) {
    lines.push('## Tasks')
    lines.push('')
    lines.push('| Task | Owner | Priority | Deadline |')
    lines.push('|------|-------|----------|----------|')
    result.tasks.forEach((t) => {
      lines.push(
        `| ${t.title.replace(/\|/g, '\\|')} | ${t.owner} | ${t.priority} | ${t.deadline} |`,
      )
    })
    lines.push('')
    lines.push('---')
    lines.push('')
  }
  if (result.risks.length > 0) {
    lines.push('## Risks')
    lines.push('')
    result.risks.forEach((r) => lines.push(`- ${r}`))
    lines.push('')
    lines.push('---')
    lines.push('')
  }
  if (result.timeline.length > 0) {
    lines.push('## Timeline')
    lines.push('')
    result.timeline.forEach((item) => {
      lines.push(
        `### ${item.date}${item.day !== item.date ? ` (${item.day})` : ''}`,
      )
      item.events.forEach((ev) => lines.push(`- ${ev}`))
      lines.push('')
    })
  }
  return lines.join('\n')
}

// ─── Clipboard helper ────────────────────────────────────────────────────────

async function copyToClipboard(text: string): Promise<void> {
  try {
    await navigator.clipboard.writeText(text)
  } catch {
    const ta = document.createElement('textarea')
    ta.value = text
    ta.style.cssText = 'position:fixed;opacity:0;pointer-events:none'
    document.body.appendChild(ta)
    ta.focus()
    ta.select()
    document.execCommand('copy')
    document.body.removeChild(ta)
  }
}

// ─── Main component ──────────────────────────────────────────────────────────

export default function ResultsSection({ result, onReset, isSharedView }: ResultsSectionProps) {
  const highCount = result.tasks.filter((t) => t.priority === 'High').length
  const confidence = calculateConfidence(result)
  const [copied, setCopied] = useState(false)
  const [pdfBusy, setPdfBusy] = useState(false)
  const copyTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const uniqueOwners = Array.from(
    new Set(
      result.tasks
        .map((t) => t.owner)
        .filter((o) => o && !['tbd', '—', '-'].includes(o.toLowerCase())),
    ),
  )

  const confidenceColor =
    confidence >= 90 ? '#22C55E' : confidence >= 70 ? '#F59E0B' : '#EF4444'
  const confidenceBg =
    confidence >= 90
      ? 'rgba(34,197,94,0.12)'
      : confidence >= 70
        ? 'rgba(245,158,11,0.12)'
        : 'rgba(239,68,68,0.12)'
  const confidenceBorder =
    confidence >= 90
      ? 'rgba(34,197,94,0.28)'
      : confidence >= 70
        ? 'rgba(245,158,11,0.28)'
        : 'rgba(239,68,68,0.28)'
  const confidenceLabel =
    confidence >= 90
      ? 'High Confidence'
      : confidence >= 70
        ? 'Medium Confidence'
        : 'Low Confidence'

  async function handleExportPdf() {
    if (pdfBusy) return
    setPdfBusy(true)
    try {
      const { exportToPdf } = await import('../lib/exportPdf')
      await exportToPdf(result)
      toast.success('PDF exported successfully')
      trackNovus('pdf_exported', {
        task_count: result.tasks.length,
        risk_count: result.risks.length,
        decision_count: result.decisions.length,
        timeline_item_count: result.timeline.length,
        has_high_priority_tasks: highCount > 0,
        confidence_score: confidence,
      })
    } catch (err) {
      console.error('[ExportPDF]', err)
      toast.error('PDF export failed — please try again')
    } finally {
      setPdfBusy(false)
    }
  }

  function handleExportMarkdown() {
    exportToMarkdown(result)
    toast.success('Markdown downloaded')
    trackNovus('markdown_exported', {
      task_count: result.tasks.length,
      risk_count: result.risks.length,
      decision_count: result.decisions.length,
      timeline_item_count: result.timeline.length,
    })
  }

  async function handleCopy() {
    await copyToClipboard(buildMarkdownString(result))
    setCopied(true)
    toast.success('Copied to clipboard')
    trackNovus('plan_copied_to_clipboard', {
      task_count: result.tasks.length,
      risk_count: result.risks.length,
      decision_count: result.decisions.length,
      timeline_item_count: result.timeline.length,
      confidence_score: confidence,
    })
    if (copyTimerRef.current) clearTimeout(copyTimerRef.current)
    copyTimerRef.current = setTimeout(() => setCopied(false), 2000)
  }

  async function handleCopyJira() {
    await copyToClipboard(buildJiraString(result))
    toast.success('Jira format copied.')
    trackNovus('jira_copied', {
      task_count: result.tasks.length,
      risk_count: result.risks.length,
      high_priority_count: highCount,
    })
  }

  async function handleCopyNotion() {
    await copyToClipboard(buildNotionString(result))
    toast.success('Notion format copied.')
    trackNovus('notion_copied', {
      task_count: result.tasks.length,
      risk_count: result.risks.length,
      decision_count: result.decisions.length,
      timeline_item_count: result.timeline.length,
    })
  }

  async function handleSharePlan() {
    const planId = `af_${Date.now()}`
    try {
      localStorage.setItem(planId, JSON.stringify(result))
      const url = `${window.location.origin}${window.location.pathname}?shared=${planId}`
      await copyToClipboard(url)
      toast.success('Share link copied.')
      trackNovus('share_plan_clicked', {
        task_count: result.tasks.length,
        plan_id: planId,
        risk_count: result.risks.length,
        confidence_score: confidence,
      })
    } catch {
      toast.error('Could not create share link.')
    }
  }

  return (
    <section className="px-6 pb-24">
      <div className="max-w-6xl mx-auto">

        {/* Shared-view banner */}
        {isSharedView && (
          <div
            className="flex items-center gap-3 px-4 py-3 rounded-xl text-sm mb-6"
            style={{
              background: 'rgba(139,92,246,0.08)',
              border: '1px solid rgba(139,92,246,0.2)',
              color: '#A78BFA',
            }}
          >
            <Share2 size={14} />
            <span>
              You&apos;re viewing a shared plan&nbsp;&mdash;&nbsp;
              <span style={{ color: '#71717A' }}>
                Share links work on this device/browser for demo mode.
              </span>
            </span>
          </div>
        )}

        {/* Section header */}
        <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 mb-8">
          <div className="flex items-start gap-3">
            <div
              className="w-9 h-9 rounded-xl flex items-center justify-center shrink-0 mt-0.5"
              style={{
                background: 'rgba(34,197,94,0.14)',
                border: '1px solid rgba(34,197,94,0.28)',
              }}
            >
              <CheckCircle2 size={17} color="#22C55E" />
            </div>
            <div>
              <div className="flex items-center gap-2 flex-wrap">
                <h2
                  className="font-bold text-lg"
                  style={{ color: '#FAFAFA', letterSpacing: '-0.02em' }}
                >
                  Action Plan Generated
                </h2>
                {/* Confidence badge */}
                <div
                  className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-semibold cursor-default select-none"
                  style={{
                    background: confidenceBg,
                    border: `1px solid ${confidenceBorder}`,
                    color: confidenceColor,
                  }}
                  title="Based on transcript clarity, detected owners, deadlines, and tasks."
                >
                  <span
                    className="w-1.5 h-1.5 rounded-full shrink-0"
                    style={{
                      background: confidenceColor,
                      boxShadow: `0 0 5px ${confidenceColor}`,
                    }}
                  />
                  {confidence}%&nbsp;·&nbsp;{confidenceLabel}
                </div>
              </div>
              <p className="text-xs mt-0.5" style={{ color: '#71717A' }}>
                {result.tasks.length} tasks&nbsp;·&nbsp;{result.decisions.length}{' '}
                decisions&nbsp;·&nbsp;{result.risks.length} risks&nbsp;·&nbsp;
                <span style={{ color: '#F87171' }}>{highCount} high priority</span>
              </p>
            </div>
          </div>

          {/* Action buttons */}
          <div className="flex items-center gap-2 flex-wrap">
            <ExportButton
              icon={copied ? <CheckCheck size={12} /> : <Copy size={12} />}
              label={copied ? 'Copied!' : 'Copy Plan'}
              onClick={handleCopy}
              hoverBg="rgba(6,182,212,0.1)"
              hoverBorder="rgba(6,182,212,0.3)"
              hoverColor="#06B6D4"
            />
            <ExportButton
              icon={<FileDown size={12} />}
              label="Markdown"
              onClick={handleExportMarkdown}
              hoverBg="rgba(34,197,94,0.08)"
              hoverBorder="rgba(34,197,94,0.28)"
              hoverColor="#4ADE80"
            />
            <ExportButton
              icon={<Download size={12} />}
              label={pdfBusy ? 'Exporting...' : 'Export PDF'}
              onClick={handleExportPdf}
              disabled={pdfBusy}
              hoverBg="rgba(139,92,246,0.1)"
              hoverBorder="rgba(139,92,246,0.28)"
              hoverColor="#A78BFA"
            />
            <button
              onClick={onReset}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold transition-all duration-200 shrink-0"
              style={{
                background: 'rgba(255,255,255,0.04)',
                color: '#A1A1AA',
                border: '1px solid rgba(255,255,255,0.08)',
              }}
              onMouseEnter={(e) => {
                const el = e.currentTarget
                el.style.background = 'rgba(139,92,246,0.1)'
                el.style.borderColor = 'rgba(139,92,246,0.28)'
                el.style.color = '#A78BFA'
                el.style.transform = 'scale(1.02)'
              }}
              onMouseLeave={(e) => {
                const el = e.currentTarget
                el.style.background = 'rgba(255,255,255,0.04)'
                el.style.borderColor = 'rgba(255,255,255,0.08)'
                el.style.color = '#A1A1AA'
                el.style.transform = 'scale(1)'
              }}
            >
              <RotateCcw size={12} />
              New Analysis
            </button>
          </div>
        </div>

        {/* ── Cards grid ── */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 mb-4">
          <ResultCard
            icon={<FileText size={15} color="#8B5CF6" />}
            iconStyle={{ background: 'rgba(139,92,246,0.14)', border: '1px solid rgba(139,92,246,0.24)' }}
            title="Executive Summary"
            className="lg:col-span-2"
          >
            <p className="text-sm leading-relaxed" style={{ color: '#A1A1AA', lineHeight: '1.8' }}>
              {result.summary}
            </p>
          </ResultCard>

          <ResultCard
            icon={<CheckCircle2 size={15} color="#22C55E" />}
            iconStyle={{ background: 'rgba(34,197,94,0.14)', border: '1px solid rgba(34,197,94,0.24)' }}
            title="Key Decisions"
          >
            <ol className="flex flex-col gap-3">
              {result.decisions.map((d, i) => (
                <li key={i} className="flex items-start gap-3">
                  <span
                    className="inline-flex items-center justify-center w-5 h-5 rounded text-[10px] font-bold shrink-0 mt-0.5"
                    style={{ background: 'rgba(34,197,94,0.14)', color: '#22C55E' }}
                  >
                    {i + 1}
                  </span>
                  <span className="text-sm leading-relaxed" style={{ color: '#A1A1AA' }}>
                    {d}
                  </span>
                </li>
              ))}
            </ol>
          </ResultCard>

          <ResultCard
            icon={<ShieldAlert size={15} color="#EF4444" />}
            iconStyle={{ background: 'rgba(239,68,68,0.14)', border: '1px solid rgba(239,68,68,0.24)' }}
            title="Risks & Blockers"
          >
            <ul className="flex flex-col gap-3">
              {result.risks.map((r, i) => (
                <li key={i} className="flex items-start gap-3">
                  <span
                    className="w-1.5 h-1.5 rounded-full shrink-0 mt-[7px]"
                    style={{ background: '#EF4444', boxShadow: '0 0 6px rgba(239,68,68,0.5)' }}
                  />
                  <span className="text-sm leading-relaxed" style={{ color: '#A1A1AA' }}>
                    {r}
                  </span>
                </li>
              ))}
            </ul>
          </ResultCard>

          <ResultCard
            icon={<HelpCircle size={15} color="#F59E0B" />}
            iconStyle={{ background: 'rgba(245,158,11,0.14)', border: '1px solid rgba(245,158,11,0.24)' }}
            title="Follow-up Questions"
          >
            <ul className="flex flex-col gap-3">
              {result.followUps.map((q, i) => (
                <li key={i} className="flex items-start gap-3">
                  <span
                    className="text-xs font-bold shrink-0 mt-0.5 tabular-nums"
                    style={{ color: '#F59E0B', minWidth: '20px' }}
                  >
                    Q{i + 1}
                  </span>
                  <span className="text-sm leading-relaxed" style={{ color: '#A1A1AA' }}>
                    {q}
                  </span>
                </li>
              ))}
            </ul>
          </ResultCard>

          <ResultCard
            icon={<Lightbulb size={15} color="#8B5CF6" />}
            iconStyle={{ background: 'rgba(139,92,246,0.14)', border: '1px solid rgba(139,92,246,0.24)' }}
            title="AI Suggestions"
          >
            <ul className="flex flex-col gap-3">
              {result.suggestions.map((s, i) => (
                <li key={i} className="flex items-start gap-3">
                  <span
                    className="inline-flex items-center justify-center w-5 h-5 rounded shrink-0 mt-0.5 text-xs font-bold"
                    style={{ background: 'rgba(139,92,246,0.14)', color: '#8B5CF6' }}
                  >
                    ↗
                  </span>
                  <span className="text-sm leading-relaxed" style={{ color: '#A1A1AA' }}>
                    {s}
                  </span>
                </li>
              ))}
            </ul>
          </ResultCard>
        </div>

        {/* ── Action Items ── */}
        <div className="mb-4">
          <ResultCard
            icon={<ListChecks size={15} color="#8B5CF6" />}
            iconStyle={{ background: 'rgba(139,92,246,0.14)', border: '1px solid rgba(139,92,246,0.24)' }}
            title="Action Items"
            subtitle={`${result.tasks.length} tasks with owners, priorities, and deadlines`}
          >
            <ActionTable tasks={result.tasks} />
          </ResultCard>
        </div>

        {/* ── Timeline ── */}
        <div className="mb-4">
          <ResultCard
            icon={<CalendarDays size={15} color="#22C55E" />}
            iconStyle={{ background: 'rgba(34,197,94,0.14)', border: '1px solid rgba(34,197,94,0.24)' }}
            title="Execution Timeline"
            subtitle="Key milestones in chronological order"
          >
            <Timeline items={result.timeline} />
          </ResultCard>
        </div>

        {/* ── Team Handoff ── */}
        <ResultCard
          icon={<Users size={15} color="#8B5CF6" />}
          iconStyle={{ background: 'rgba(139,92,246,0.14)', border: '1px solid rgba(139,92,246,0.24)' }}
          title="Team Handoff"
          subtitle="Collaboration-ready workflow"
        >
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
            {/* Assigned Owners */}
            <div>
              <p
                className="text-xs font-semibold mb-3"
                style={{ color: '#52525B', textTransform: 'uppercase', letterSpacing: '0.06em' }}
              >
                Assigned Owners
              </p>
              <div className="flex flex-col gap-2">
                {uniqueOwners.length > 0 ? (
                  uniqueOwners.slice(0, 5).map((owner, i) => (
                    <div key={i} className="flex items-center gap-2">
                      <div
                        className="w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold shrink-0"
                        style={{ background: 'rgba(139,92,246,0.2)', color: '#A78BFA' }}
                      >
                        {owner.charAt(0).toUpperCase()}
                      </div>
                      <span className="text-sm" style={{ color: '#D4D4D8' }}>
                        {owner}
                      </span>
                    </div>
                  ))
                ) : (
                  <span className="text-sm" style={{ color: '#52525B' }}>
                    No owners detected
                  </span>
                )}
              </div>
            </div>

            {/* Export Formats */}
            <div>
              <p
                className="text-xs font-semibold mb-3"
                style={{ color: '#52525B', textTransform: 'uppercase', letterSpacing: '0.06em' }}
              >
                Export Formats
              </p>
              <div className="flex flex-col gap-2">
                <ExportButton
                  icon={
                    <span
                      style={{
                        fontSize: '11px',
                        fontWeight: 700,
                        fontFamily: 'monospace',
                        lineHeight: 1,
                      }}
                    >
                      J
                    </span>
                  }
                  label="Copy Jira"
                  onClick={handleCopyJira}
                  hoverBg="rgba(0,101,255,0.1)"
                  hoverBorder="rgba(0,101,255,0.3)"
                  hoverColor="#4C9AFF"
                />
                <ExportButton
                  icon={<FileText size={12} />}
                  label="Copy Notion"
                  onClick={handleCopyNotion}
                  hoverBg="rgba(255,255,255,0.06)"
                  hoverBorder="rgba(255,255,255,0.18)"
                  hoverColor="#FAFAFA"
                />
              </div>
              <p className="text-xs mt-3" style={{ color: '#3F3F46', lineHeight: '1.5' }}>
                Paste directly into your PM tools
              </p>
            </div>

            {/* Share */}
            <div>
              <p
                className="text-xs font-semibold mb-3"
                style={{ color: '#52525B', textTransform: 'uppercase', letterSpacing: '0.06em' }}
              >
                Share Plan
              </p>
              <ExportButton
                icon={<Share2 size={12} />}
                label="Share Plan"
                onClick={handleSharePlan}
                hoverBg="rgba(34,197,94,0.1)"
                hoverBorder="rgba(34,197,94,0.28)"
                hoverColor="#4ADE80"
              />
              <p className="text-xs mt-3" style={{ color: '#3F3F46', lineHeight: '1.5' }}>
                Share links work on this device/browser for demo mode.
              </p>
            </div>
          </div>
        </ResultCard>
      </div>
    </section>
  )
}

// ─── Shared export button ────────────────────────────────────────────────────

function ExportButton({
  icon,
  label,
  onClick,
  disabled,
  hoverBg,
  hoverBorder,
  hoverColor,
}: {
  icon: React.ReactNode
  label: string
  onClick: () => void
  disabled?: boolean
  hoverBg: string
  hoverBorder: string
  hoverColor: string
}) {
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-semibold transition-all duration-200 shrink-0 disabled:opacity-50 disabled:cursor-not-allowed"
      style={{
        background: 'rgba(255,255,255,0.04)',
        color: '#A1A1AA',
        border: '1px solid rgba(255,255,255,0.08)',
      }}
      onMouseEnter={(e) => {
        if (disabled) return
        const el = e.currentTarget
        el.style.background = hoverBg
        el.style.borderColor = hoverBorder
        el.style.color = hoverColor
        el.style.transform = 'scale(1.02)'
      }}
      onMouseLeave={(e) => {
        const el = e.currentTarget
        el.style.background = 'rgba(255,255,255,0.04)'
        el.style.borderColor = 'rgba(255,255,255,0.08)'
        el.style.color = '#A1A1AA'
        el.style.transform = 'scale(1)'
      }}
    >
      {icon}
      {label}
    </button>
  )
}

// ─── Shared card wrapper ─────────────────────────────────────────────────────

function ResultCard({
  icon,
  iconStyle,
  title,
  subtitle,
  children,
  className = '',
}: {
  icon: React.ReactNode
  iconStyle: React.CSSProperties
  title: string
  subtitle?: string
  children: React.ReactNode
  className?: string
}) {
  return (
    <div
      className={`rounded-3xl p-6 ${className}`}
      style={{
        background: '#18181B',
        border: '1px solid rgba(255,255,255,0.07)',
        boxShadow: '0 4px 24px rgba(0,0,0,0.2)',
        transition: 'transform 300ms ease-out, border-color 300ms ease-out, box-shadow 300ms ease-out',
      }}
      onMouseEnter={(e) => {
        const el = e.currentTarget
        el.style.transform = 'translateY(-2px)'
        el.style.borderColor = 'rgba(139,92,246,0.2)'
        el.style.boxShadow = '0 12px 40px rgba(0,0,0,0.32), 0 0 0 1px rgba(139,92,246,0.1)'
      }}
      onMouseLeave={(e) => {
        const el = e.currentTarget
        el.style.transform = 'translateY(0)'
        el.style.borderColor = 'rgba(255,255,255,0.07)'
        el.style.boxShadow = '0 4px 24px rgba(0,0,0,0.2)'
      }}
    >
      <div className="flex items-start gap-3 mb-5">
        <div
          className="flex items-center justify-center w-8 h-8 rounded-lg shrink-0"
          style={iconStyle}
        >
          {icon}
        </div>
        <div>
          <h3 className="font-semibold text-sm" style={{ color: '#FAFAFA' }}>
            {title}
          </h3>
          {subtitle && (
            <p className="text-xs mt-0.5" style={{ color: '#71717A' }}>
              {subtitle}
            </p>
          )}
        </div>
      </div>
      {children}
    </div>
  )
}
